name: Main

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  unit-tests:
    permissions:
      pull-requests: write
      contents: write
      statuses: write
      checks: write
      actions: write

    uses: ./.github/workflows/unit.yml
